### ISSUE TITLE
CapSense Initialization fails when using quickstart example code

### ISSUE THREAD

**Issue by ralphjy** [Infineon/sensor-motion-bmi160#1]
I am using the quickstart example code on a PSoC 6 WiFi-BT Pioneer Kit with CapSense.  When I add the code, the CapSense Initialization fails.  I stepped through the IMU initialization and that seemed to work.  I am using Modus Toolbox 2.2.

Is there any particular initialization order with the different peripherals?  I noticed that CapSense is using ezi2c?

Thanks,

Ralph

**Comment by rmbk19** [comment]
Hi @ralphjy,

I believe this query is handled in this thread - [CapSense Initialization Failure using Modus Toolbox ](https://community.cypress.com/t5/PSoC-6-MCU/CapSense-Initialization-Failure-using-Modus-Toolbox/m-p/264584)
Please let me know if in case this is a different query.

Regards,
Rakshith

**Comment by ralphjy** [comment]
This is the same issue and has been resolved.

Thanks,
Ralph
